name: getm2-notebooks
channels:
  - conda-forge
dependencies:
  - python=3.8
  - fortran-compiler
  - xarray
  - jupyterlab
  - numpy
  - matplotlib
  - scipy
  - ipympl
  - netcdf4
  - pyyaml
  - mpi4py
  - dotenv
